### ISSUE TITLE
Add "some super sweet catchphrase"

### ISSUE THREAD

**Issue by pdehaan** [mozilla/pulse#112]
Currently (**pulse@0.9.2**) the add-on description in about:addons says:

> _"Some super sweet catchphrase"_

We should add some basic description or something.

![add-ons_manager](https://cloud.githubusercontent.com/assets/557895/23178059/e3a2ccd6-f81d-11e6-91d3-6939a1ceff1e.png)

Not sure if we just use the [Pulse Test Pilot page](https://testpilot.dev.mozaws.net/experiments/pulse) overview:

> _"We’re building the next generation of Firefox, and we’re focusing on real-world speed and performance. Pulse lets you give our engineers feedback about your experience on websites that work well in Firefox and on websites that don’t."_

**Comment by chuckharmston** [comment]
Yep! Just waiting on final content (@ckprice is this it?), will be part of the 1.0 release.

**Comment by ckprice** [comment]
@chuckharmston yeah just confirmed that we should expect no new changes from what's currently in the YAML file for this (and Snooze Tabs).
