### ISSUE TITLE
Feedback TextArea should not be resizeable

### ISSUE THREAD

**Issue by pdehaan** [mozilla/pulse#119]
![add-ons_manager](https://cloud.githubusercontent.com/assets/557895/23193060/ceaf68dc-f85b-11e6-8539-75d749aa1c52.png)

Currently, when filling out feedback (after giving a star rating), you can get into weird cases where the textarea is resizable and then the DOM repaints and things appear masked by the popup.

![ivanka_trump_steps_into_role_behind_her_father_-_cnnpolitics_com](https://cloud.githubusercontent.com/assets/557895/23193051/bf1d9d08-f85b-11e6-8712-9f45eee7b5d4.png)

Possibly https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea#Resizable_textareas

**Comment by SoftVision-EmilPasca** [comment]
This is how it looks like when resizing the other way:
![pulse_resizing_issue](https://cloud.githubusercontent.com/assets/20083658/23260412/66e52874-f9da-11e6-8790-77b3a0f24ea0.gif)
