### ISSUE TITLE
If the Pulse icon is clicked multiple times, a new pop-up is opened for each click

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/pulse#123]
[Affected versions]:
- Firefox 51.0.1	
- Pulse 1.0.2

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have Test Pilot add-on installed on a new clean profile.
- Have Pulse add-on installed on the created profile

[Steps to reproduce]:
1. Open Firefox with the profile from prerequisites an navigate to any website.
2. Click multiple times on the Pulse icon from the address bar.  
3. Observe the browser behavior.

[Expected result]:
- Only one pop-up is opened even if the button is clicked multiple times.

[Actual result]:
- A new pop-up is opened for each click.

[Notes]:
- Here is a screen recording with the issue: https://goo.gl/Jz4T2l

**Comment by chuckharmston** [comment]
Unfortunately I think this is an upstream bug; the mechanisms by which the popup is created and hidden are controlled by Firefox.
