### ISSUE TITLE
testpilot.firefox.com should not be whitelisted

### ISSUE THREAD

**Issue by davidhedlund** [mozilla/pulse#129]
First thing I noticed was that I was not able to rate https://testpilot.firefox.com/ and https://testpilot.firefox.com/experiments/pulse.

The test pilot website should of course also be rated.

**Comment by chuckharmston** [comment]
Thanks for the report! I completely agree that Test Pilot should also participate.

Unfortunately, websites that are granted special access to install add-ons directly (including Test Pilot and [addons.mozilla.org](addons.mozilla.org)) are unable to have WebExtension pageActions or content scripts loaded into them. This isn't an exemption built into Pulse—we try to load it into [all URLs](https://github.com/mozilla/pulse/blob/7deb3c912fca6eb85c7453a0462610f6aaaf9eab/src/webextension/manifest.json#L22)—but actually a security precaution to prevent WebExtensions from loading malicious add-ons with more permissions via Test Pilot.

Unfortunately I'll have to close this.

**Comment by davidhedlund** [comment]
@chuckharmston Why not just disable it completely on this domain instead of indicate a false-positive icon?

**Comment by chuckharmston** [comment]
@davidhedlund I'm a bit confused—are you seeing the Pulse icon in the URL bar while visiting Test Pilot? Would you mind providing a screenshot of that?
