### ISSUE TITLE
Website ratings missing

### ISSUE THREAD

**Issue by davidhedlund** [mozilla/pulse#130]
Currently its only possible to rate websites with Pulse, not view their ratings.

Web of Trust was recently banned from AMO for good reasons as they sold the user submitted information to companies. Pulse can replace that add-on but a user website rating website should be available.

**Comment by chuckharmston** [comment]
Thanks for the thoughts!

Pulse isn't exactly intended to be a reputation or review service as Web of Trust was. Instead, we're looking to align user sentiment (measured similarly) with [additional performance numbers](https://github.com/mozilla/pulse/blob/master/docs/metrics.md#pulse-submitted), to help us focus our attention as we [double down on Firefox performance](https://wiki.mozilla.org/Quantum).

That sort of data isn't as appropriate for public display, so unfortunately I'll need to close this.

**Comment by davidhedlund** [comment]
@chuckharmston Can you make this clear in the description of the project?

**Comment by chuckharmston** [comment]
@davidhedlund Would you mind pointing out a place where you feel it could be improved? This seems quite clear to me:

> We’re building the next generation of Firefox, and we’re focusing on real-world speed and performance. Pulse lets you give our engineers feedback about your experience on websites that work well in Firefox and on websites that don’t.

**Comment by davidhedlund** [comment]
@chuckharmston Add to that

> However, pulse isn't intended to be a reputation or review service.
