### ISSUE TITLE
Tabs are loaded without being selected on Startup

### ISSUE THREAD

**Issue by Ludomancer** [mozilla/pulse#132]
I've noticed that tabs except for Pinned tabs aren't loaded on startup until they are actually switched/clicked to. But Snoozed Tabs "Next Open" option does not respect this feature/option. This slows down Firefox startup time and responsiveness.

I think it should behave the same as other tabs to prevent any slowdown during startup. This is especially an issue if multiple tabs were snoozed to "Next Open".

I think(not sure) the variable/option I'm talking about is: browser.sessionstore.restore_on_demand

**Comment by chuckharmston** [comment]
Hi @Nidre, looks like you meant to file this on the Snooze Tabs repository. Copied the bug over there for you: https://github.com/bwinton/SnoozeTabs/issues/219
