### ISSUE TITLE
Tab Context Menu options does not work

### ISSUE THREAD

**Issue by Ludomancer** [mozilla/pulse#133]
What happened;

1. I've right clicked on a tab other than my currently active tab.
2. Selected Snooze tab until Tomorrow
3. Nothing happened.

Tab should've happened

1. I've right clicked on a tab other than my currently active tab.
2. Selected Snooze tab until Tomorrow
3. Tab should've been snoozed and removed from tab bar.

Note: This does work if I disable "Ask for confirmation when snoozing tabs" option. I **guess** the confirmation is displayed in the inactive tab which makes it impossible to respond to without switching to it.

**Comment by chuckharmston** [comment]
Hi @Nidre, looks like you meant to file this on the Snooze Tabs repository. Copied the bug over there for you: https://github.com/bwinton/SnoozeTabs/issues/220

**Comment by Ludomancer** [comment]
@chuckharmston 

Yeap you are right. :/
