### ISSUE TITLE
Pop-up survey questions are numbered

### ISSUE THREAD

**Issue by Softvision-VladBacia** [mozilla/pulse#141]
**[Affected versions]:**
-Firefox 52.0 and up
-Pulse v1.1 RC

**[Affected Platforms]:**
-All Windows
-All Mac
-All Linux

**[Prerequisites]:**
-Pulse v1.1 RC was previously installed on a clean profile.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Navigate to a http or https webpage.
3. Click on Pulse icon from the URL bar.
4. Give the page a rating in order to go to the next part of the survey.
5. Observe the numbering and padding.

**[Expected result]:**
- The question numbers are hidden for the pop-up survey.

**[Actual result]:**
- The question numbers are displayed for the pop-up survey.

**[Notes]:**
- Recording of the issue:

![question numbering](https://cloud.githubusercontent.com/assets/9248513/24447033/445fe0ec-1478-11e7-8cd6-9fe5ecd607f4.gif)

**Comment by chuckharmston** [comment]
This blocks 1.1.

**Comment by Softvision-VladBacia** [comment]
This issue has been verified on Pulse 1.1_RC2 and it is no more reproducible.
