### ISSUE TITLE
Pulse icon from URL bar is not displayed after the add-on has been reenabled

### ISSUE THREAD

**Issue by Softvision-VladBacia** [mozilla/pulse#142]
**[Affected versions]:**
-Firefox 52.0 and up
-Pulse v1.1 RC

**[Affected Platforms]:**
-All Windows
-All Mac
-All Linux

**[Prerequisites]:**
-Pulse v1.1 RC was previously installed on a clean profile.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Navigate to a http or https webpage.
3. Open another tab with `about:addons -> Extensions` screen.
4. Disable and Enable the Pulse add-on and quickly go to the opened page from step 2.
5. After a few seconds the Heartbeat notification is displayed.
6. Refresh the page.

**[Expected result]:**
5. The Heartbeat notification is displayed but without the Pulse icon from URL bar.
6. After the page refresh, the Heartbeat notification and the Pulse icon from URL bar are displayed.

**[Actual result]:**
- After the add-on has been enabled, the Pulse icon from URL bar is displayed.

**[Notes]:**
- If the page is refreshed, the Pulse icon from URL bar is displayed and also the Heartbeat notification.

![refresh](https://cloud.githubusercontent.com/assets/9248513/24456277/36cc3070-149b-11e7-9be1-b446ad277229.gif)

**Comment by chuckharmston** [comment]
This is by design; the URL bar icon is only shown if Pulse has been continuously installed since the beginning of the page load. If you refresh the page from here, it should be shown appropriately.
