### ISSUE TITLE
The survey is not opened in a new tab after rating the page in the Heartbeat notification

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [mozilla/pulse#144]
[Affected versions]:
- Firefox 52.0 and up
- Pulse v1.1 RC

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Pulse v1.1 RC was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Have two tabs opened, in one navigate to a http or https webpage.
3. In the other tab navigate to about:addons.
4. Disable and re-enable the Pulse addon in about:addons.
5. Quickly switch to the tab with the opened webpage.
6. Rate the page from the Heartbeat notification.
7. Observe the browser behavior.

[Expected result]:
- The Heartbeat notification is dismissed and a new tab is opened with the Pulse survey.

[Actual result]:
- The Heartbeat notification is dismissed, however the Pulse survey is not opened in a new tab.

[Notes]:
- The following error is displayed in the Browser Console:
`[pulse.sdk.index] SDK startup  index.js:294:8
[pulse.sdk.index] WebExtension startup  index.js:294:8
[pulse.sdk.index] Received survey url moz-extension://40f06fe6-1d8f-4575-9c73-7a3fed7e356e/survey/index.html  index.js:294:8
[pulse.sdk.lib.notify] Prompted Object { method: "pulse-prompted", id: "ce9ca274-8198-4c36-94e8-4260574bcf67", type: "random" }  index.js:294:8
TypeError: _simpleStorage.storage.id is undefined[Learn More]`
- Attached a screen recording of the issue:
![issue_pulse_survey](https://cloud.githubusercontent.com/assets/20083658/24459795/02ff1802-14a5-11e7-8820-2705ce8f756d.gif)

**Comment by chuckharmston** [comment]
This blocks 1.1

**Comment by SoftVision-EmilPasca** [comment]
The issue is no longer reproducible on Pulse-1.1_RC3.xpi.
