### ISSUE TITLE
Heartbeat notification and Pulse URL icon are displayed in PBM

### ISSUE THREAD

**Issue by Softvision-VladBacia** [mozilla/pulse#146]
**[Affected versions]:**
-Firefox 52.0 and up
-Pulse v1.1 RC

**[Affected Platforms]:**
-All Windows
-All Mac
-All Linux

**[Prerequisites]:**
-Pulse v1.1 RC was previously installed on a clean profile.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites in Private Browsing Mode.
2. Navigate to a http or https webpage.
3. Observe the Pulse icon from the URL bar.

**[Expected result]:**
- In Private Browsing Mode the Pulse icon should not be displayed in the URL bar and also the Heartbeat notification.

**[Actual result]:**
- Heartbeat notification and Pulse URL icon are displayed in PBM.

**Comment by chuckharmston** [comment]
This blocks 1.1.

**Comment by Softvision-VladBacia** [comment]
This issue has been verified on Pulse 1.1_RC2 and it is no more reproducible.
