### ISSUE TITLE
Various UI issues if the theme is changed to High Contrast Black (Windows)

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/pulse#148]
[Affected versions]:
- Firefox 52.0 and up
- Pulse 1.1 RC 

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Pulse v1.1 RC was previously installed on a clean profile.
- High Contrast Black OS theme on Windows is enabled.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisite and navigate to any http or https website.
2. Click on the "Pulse" button from the URL bar.
3. Check if all items are visible.
4. Hover and click an invisible rating star.
5. Click on "Select one..." and observe the way the options are displayed.

[Expected result]:
3. The text, "Pulse" icon and rating stars are visible.
5. "Select one..." text options from the dropdown are visible.

[Actual result]:
3. The "Pulse" icon and rating stars are not visible.
5. "Select one..." text options from the dropdown are not visible unless hovering them.

[Notes]: 
- Please see the Screen Cast attached:

![black](https://cloud.githubusercontent.com/assets/26000308/24461367/8828b30e-14a9-11e7-9fde-73ab8226ec06.gif)

**Comment by chuckharmston** [comment]
This is really unfortunate, but I'm not sure if there's much that can be done here.

@bwinton, any ideas if WebExtension UI can be responsive to themes?

**Comment by bwinton** [comment]
Nope, it can’t.  Although [it’s planned](https://docs.google.com/document/d/1PsbAvmagGsMGoX3q6xQ94O6-Ke4evIdIEbmEmNqb-rQ/) for [some point](https://bugzilla.mozilla.org/show_bug.cgi?id=1349944) in [the future](https://bugzilla.mozilla.org/show_bug.cgi?id=1329242)…  🙂

**Comment by chuckharmston** [comment]
I knew you'd be the right person to ask. Thanks for the consult!

Unfortunately, I'll have to close for that. Will look into this when it's possible!
