### ISSUE TITLE
pageAction should only be displayed for http and https protocols.

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [mozilla/pulse#149]
[Affected versions]:
- Firefox 52.0 and up
- Pulse v1.1 RC

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Pulse v1.1 RC was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to a local file.
3. Observe the Pulse icon.

[Expected result]:
- The Pulse icon should not be displayed for local files opened in the browser.

[Actual result]:
- The Pulse icon is displayed and the user can submit feedback via de Pop-up survey.

[Notes]:
- Attached a screen recording of the issue:
![issue_local_files](https://cloud.githubusercontent.com/assets/20083658/24461891/44f7e5f8-14ab-11e7-9538-e5721d71fd1d.gif)

**Comment by chuckharmston** [comment]
Renamed to reflect the proper fix for this, marked to ship with 1.1.

**Comment by SoftVision-EmilPasca** [comment]
The issue is no longer reproducible on Pulse-1.1_RC2.xpi and RC3.
