### ISSUE TITLE
Timestamp reflects the time at which the page was last refreshed and not the time when the survey was submitted

### ISSUE THREAD

**Issue by Softvision-VladBacia** [mozilla/pulse#150]
**[Affected versions]:**
-Firefox 52.0 and up
-Pulse v1.1 RC

**[Affected Platforms]:**
-All Windows
-All Mac
-All Linux

**[Prerequisites]:**
-Pulse v1.1 RC was previously installed on a clean profile.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Navigate to a http or https webpage.
3. Wait 5 minutes.
4. Complete the Pulse survey for the page from step 2.
5. Observe in Developer Tools console the timestamp at which the survey was submitted.

**[Expected result]:**
- The timestamp reflects the time at which the survey was submitted.

**[Actual result]:**
- The timestamp submitted in the call reflects the time at which the page was refreshed last time.

**[Notes]:**
- Here is a recording of the issue:

![timestamp](https://cloud.githubusercontent.com/assets/9248513/24463829/93f78046-14b0-11e7-95ea-83d76a32b31d.gif)

**Comment by chuckharmston** [comment]
That is, in fact, by design. Since the packets are reports on the experience on that specific page, it makes sense to report the timestamp of the page.

Telemetry itself tracks the submission time, so both numbers are considered.
