### ISSUE TITLE
Highlight state is missing when hovering the "Pulse" button from URL bar

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/pulse#156]
[Affected versions]:
- Firefox 52.0 and up
- Pulse v1.1 RC

[Affected Platforms]:
- All Windows
- All MAC OS
- All Linux

[Prerequisites]:
- Pulse v1.1 RC was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to a http or https website.
3. Hover the "Pulse" button from the URL bar and observe if any change is made.

[Expected result]:
- Highlight state of the button is displayed when hovering the "Pulse" button.

[Actual result]:
- "Pulse" button from URL bar is gray when hovered.

[Notes]:
- Other buttons from the URL bar (Reload, Reader View, Pop up blocking etc) change their color into blue when hovering them.
- Please see the Screen Cast attached:

![hover](https://cloud.githubusercontent.com/assets/26000308/24506264/96a1083e-1565-11e7-9fbb-20bf84fffb0d.gif)

**Comment by chuckharmston** [comment]
Unfortunately, this isn't something this type of extension is able to do.
