### ISSUE TITLE
Long URL is not entirely displayed in the survey

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/pulse#157]
[Affected versions]:
- Firefox 52.0 and up
- Pulse v1.1 RC

[Affected Platforms]:
- All Windows
- All MAC OS
- All Linux

[Prerequisites]:
- Pulse v1.1 RC was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to http://www.thelongestdomainnameintheworldandthensomeandthensomemoreandmore.com/
3. Click on the "Pulse' button and observe the URL in the survey.

[Expected result]:
- The URL is entirely displayed.

[Actual result]:
- A part of the URL is not displayed.

[Notes]:
- In New Tab survey, the URL spreads outside the survey box.
- Please see the Screenshot attached:

![long url](https://cloud.githubusercontent.com/assets/26000308/24507032/11ea2dac-1568-11e7-95fb-c59604a144ba.png)

**Comment by Softvision-VladBacia** [comment]
This issue has been verified on Pulse 1.1_RC2 and it is no more reproducible.
