### ISSUE TITLE
The "Pulse" button is no longer displayed on the URL bar after Google maps website is completely loaded

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/pulse#158]
[Affected versions]:
- Firefox 52.0 and up
- Pulse v1.1 RC

[Affected Platforms]:
- All Windows
- All MAC OS
- All Linux

[Prerequisites]:
- Pulse v1.1 RC was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to https://maps.google.com
3. Observe the behavior of the "Pulse" button from the URL bar.

[Expected result]:
- The "Pulse" button is displayed after the page is loaded.

[Actual result]:
- The "Pulse" button is displayed after the page is completely loaded for 1-2 seconds and then disappears.

[Notes]:
- After reloading the website, the "Pulse" icon appears again.
- The button also disappears after changing the Earth/Maps view mode.
- Please see the Screen Cast attached:

![maps](https://cloud.githubusercontent.com/assets/26000308/24507809/2ec9a7de-156a-11e7-9567-7a54127d2faa.gif)

**Comment by chuckharmston** [comment]
This is a red herring for the same issue in #151. Closing as a duplicate.
