### ISSUE TITLE
Heartbeat notifications are displayed one over the other if the first one hasn't been dismissed

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [mozilla/pulse#164]
[Affected versions]:
- Firefox 52.0 and up
- Pulse 1.1_RC3

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Pulse 1.1_RC3 RC was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to a http or https webpage.
3. Wait until two Heartbeat notification are displayed for the same webpage (Wait ~450 seconds).

[Expected result]:
- The first notification is overwritten by the second one and there will be only one Heartbeat notification; or the first notification is displayed and all notifications that will follow will be silent until the user accesses the survey from the notification.

[Actual result]:
- Heartbeat notifications pile up and are displayed one over the other.

[Notes]:
- For every 225 seconds another heartbeat notification is added.
- When pressing the "X" button from the notification, the top one is dismissed and the next one is displayed.
- When rating the notification, the top one is dismissed and the survey is opened in a new tab, but the other notification still remain displayed.
- Attached a screen recording of the issue:
![pulse_heartbeat_issue](https://cloud.githubusercontent.com/assets/20083658/24613997/9cf2e4d4-1892-11e7-995e-b6fbc14c6f9e.gif)

**Comment by chuckharmston** [comment]
I'm going to bucket this with https://github.com/mozilla/pulse/issues/143#issuecomment-290217672, as it would use a similar technique.

It's certainly a legitimate bug, but since the real-world time between notifications is over 30 hours, the real-world scenarios where a notification would be opened in the same tab as another are very minimal.
