### ISSUE TITLE
Missing payload fields in re:dash.

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/pulse#171]
The current list of fields, divined by `DESCRIBE default.txp_pulse`:

- `method`
- `id`
- `type`
- `object`
- `category`
- `variant`
- `details`
- `sentiment`
- `reason`
- `adblocker`
- `addons`
- `channel`
- `hostname`
- `language`
- `opentabs`
- `openwindows`
- `platform`
- `protocol`
- `telemetryid`
- `timercontentloaded`
- `timerfirstinteraction`
- `timerfirstpaint`
- `timerwindowload`
- `inner_timestamp`
- `fx_version`
- `creation_date`
- `test`
- `variants`
- `timestamp`
- `version`
- `submission_date`

This is missing the following fields from the `pulse-submitted` payload:

- `requests`
- `disconnectRequests`
- `consoleErrors`
- `e10sStatus`
- `e10sProcessCount`
- `trackingProtection`

These fields are [all documented](https://github.com/mozilla/pulse/blob/master/docs/metrics.md#pulse-submitted).

**Comment by sunahsuh** [comment]
@harterrt graciously has agreed to take this over 🙏

**Comment by harterrt** [comment]
I'm scoping this out now. I expect to have this job updated and backfilled by Monday EOD. Thanks!

**Comment by chuckharmston** [comment]
Thanks, @harterrt!

Let me know if there's anything I can do to help. I know the `requests` bit of the payload is a bear; I'd be happy to change the format so long as we're able to backfill all the existing data.

**Comment by harterrt** [comment]
OK. This should be resolved as soon as re:dash catches up.

I've moved the ETL for this table to [this repository](https://github.com/harterrt/pulse_etl). I added the missing fields in these two commits: [requests](https://github.com/harterrt/pulse_etl/commit/dfb2da5d80fb5a4a8bdc5d82bf45efc7d31bd63a), [the rest](https://github.com/harterrt/pulse_etl/commit/74008feac4f41441d266fd10cd810880b887ed1a). I'm going to kick off a job to backfill this data tonight.

**Comment by harterrt** [comment]
Cool, it looks like the data is there.
https://sql.telemetry.mozilla.org/queries/4151/source
