### ISSUE TITLE
Some methods not captured in re:dash after 4/5

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/pulse#173]
re:dash has not gotten any new pings of the following methods since 4/5:

- `pulse-submitted`
- `pulse-prompted`
- `pulse-dismissed`

This can be seen here: https://sql.telemetry.mozilla.org/queries/4094/source

4/5 was the day before our most recent release, so it's likely related to that. However, pings are being sent, so it seems likely to be an issue on the collection side.

Example pings from my testing, gathered from about:telemetry: https://gist.github.com/chuckharmston/892864f4ab08bd5a6401ed17ddfe7351

CC @harterrt @sunahsuh

**Comment by harterrt** [comment]
This is related to [Issue 174](https://github.com/mozilla/pulse/issues/174). This morning, the most recent update to the testpilot data appeared to be 2017-04-05. I backfilled this data earlier today so this should be fixed when re:dash catches up.

**Comment by chuckharmston** [comment]
@harterrt Thank you for looking!

That's not quite congruent with the results of the above-linked query, which shows reports from some methods having pings as recently as yesterday:

![screen shot 2017-04-10 at 9 19 08 am](https://cloud.githubusercontent.com/assets/23885/24884175/7d26d0a2-1e05-11e7-9114-d649d6bbb473.png)

(Screenshot from this morning.)

Is it possible that the updates were only affecting specific methods?

**Comment by harterrt** [comment]
Take a look at [this query](https://sql.telemetry.mozilla.org/queries/4144/source) which reports the most recent submission_date for a given method. submission_date is usually a safer bet because it's based on our servers' clocks instead of the client clocks.

**Comment by harterrt** [comment]
This appears to be resolved:
https://sql.telemetry.mozilla.org/queries/4152/source
