### ISSUE TITLE
Intemittent data outages

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/pulse#174]
Looking at these charts:

- https://sql.telemetry.mozilla.org/queries/4051#8157
- https://sql.telemetry.mozilla.org/queries/4095#8166

There appear to be a number of days with lossy data:

- March 5
- March 18
- March 28
- April 1
- April 2
- April 4

CC @harterrt @sunahsuh

**Comment by harterrt** [comment]
Thanks, Chuck. I'll take a look and backfill these dates. I'll probably be able to get to this today.

**Comment by harterrt** [comment]
Just backfilled the data for these dates. Re:dash should catch up by EOD.
