### ISSUE TITLE
Survey UX

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/pulse#59]
Tracking issue for the UX for the survey, which @sevaan is so graciously working on.

**Comment by sevaan** [comment]
First go-round wireframes: https://mozilla.invisionapp.com/share/8DA7UUKZF

**Comment by sevaan** [comment]
Walkthrough (Arrow through screens): https://mozilla.invisionapp.com/share/AXA9UHW7Q
Spec: https://mozilla.invisionapp.com/share/B6ABYQMG2

**Comment by sevaan** [comment]
[SVG Assets (.zip)](https://github.com/mozilla/pulse/files/755260/Assets.zip)
