### ISSUE TITLE
Tab and window IDs don't always line up between WebExtension and SDK sides.

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/pulse#78]
I've been working under the assumption that numeric ID collected from [WebExtension `Tab` objects](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/Tab) matches the one available [from SDK add-ons](https://developer.mozilla.org/en-US/Add-ons/SDK/High-Level_APIs/tabs#id). This doesn't appear to always be the case.

**Comment by chuckharmston** [comment]
I've been attempting to determine the tab from the SDK side by constructing an ID as a string in the form `-winId-tabId`, where `tabId` is the tab's ID as passed along by the WebExtension, and `winId` is the window ID for that tab, passed in the same way.

https://github.com/mozilla/pulse/blob/master/src/lib/utils.js#L14

It seems to work 100% of the time if there has only been one window opened during the browser session, but starts falling apart if multiples have been.

**Comment by chuckharmston** [comment]
The business need here: to determine from the SDK side the tab and window from which a WebExtension `pageAction` was opened, in order to further analyze it. I'm currently doing this by passing the window and tab ID as querystring parameters:

https://github.com/mozilla/pulse/blob/master/src/webextension/lib/util.js#L7-L11

Which I then collect and include in the message sent to the SDK when the form within is submitted:

https://github.com/mozilla/pulse/blob/master/src/webextension/survey/lib/submit.js#L13-L22

**Comment by chuckharmston** [comment]
One possibility: whenever the survey is launched, generate and ship a unique ID to the SDK, which is also passed along in the querystring of the survey. When received, the SDK side can store the active tab and window in simple-storage, then retrieve them again when the survey is submitted.

**Comment by chuckharmston** [comment]
Reopening pending further testing.

**Comment by chuckharmston** [comment]
https://github.com/mozilla/pulse/commit/7b5e503efce7efdc0ccd38acd6404177c3fb2ea1 fixes this.

**Comment by ghost** [comment]
🎆
