### ISSUE TITLE
Unable to get request filesize from WebExtension webRequest APIs

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/pulse#89]
I spent a few hours last night poking at various mechanisms to monitor network requests from a page. My findings:

- I'd been planning to lean on the [`webRequest`](https://developer.mozilla.org/Add-ons/WebExtensions/API/webRequest) API; this is suitably high-level and has everything we need for the [`pulse-submitted`](https://github.com/mozilla/pulse/blob/master/docs/metrics.md#pulse-submitted) ping, except for the size of the request (thanks, @rhelmer and Kris).
    - You can often use the `Content-Length` header to get this information.
    - This fails when `Transfer-Encoding: chunked`, for obvious reasons.
- There are no devtools APIs that extensions can use to pull data from where they are already collected (thanks, @janodvarko).
- I can use an [`nslStreamListener`](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Reference/Interface/NsIStreamListener), but it's very low-level (XPCOM components), would be difficult to resolve with the higher-level APIs (e.g. aligning requests with tabs and windows). It's doable, but outside of my comfort zone, especially on this timeline.

Proposal: we collect the data as planned, using `Content-Length` for file sizes, and include counts of `null` values for each set, and the mean of the ones with sizes. So instead of:

```
"js":   { "num": 18,   "size": 2376198,  "time": 274  }
```

We might have:

```
"js":   { "num": 18,   "size": { "total": 2376198, "null": 5, "mean": 182784.46 },  "time": 274  }
```

(`mean` being equal to `size.total / ( num - size.null)`)

An alternative would be to extrapolate based on the transfer time of other assets on the page. If a chunked request takes 300ms to complete, and a 1kb non-chunked request completes in 150ms, we can guess that the chunked one was 2kb. Horribly lossy data, but at this scale it might be good enough.

@digitarald Thoughts?

**Comment by digitarald** [comment]
Resource Timing should include all that, including details on if a resource was loaded from cache: https://developer.mozilla.org/en-US/docs/Web/API/Resource_Timing_API/Using_the_Resource_Timing_API

**Comment by jaredhirsch** [comment]
You can lean on the hidden window to get access to the Performance API from an SDK addon:

```js
Services.appShell.hiddenDOMWindow.Performance
```

**Comment by chuckharmston** [comment]
@digitarald unfortunately, without access to the response headers, the performance APIs force us to do categorization by looking at file extensions, which would be obviously unreliable. Still noodling on this one.

**Comment by digitarald** [comment]
Doesn't [resource timing](https://www.w3.org/TR/resource-timing-1/#dom-performanceresourcetiming-initiatortype) cover those categories? `performance.getEntriesByType("resource").map(entry => entry.initiatorType)`

**Comment by chuckharmston** [comment]
> Doesn't resource timing cover those categories?

@digitarald Not quite; that returns an indicator of what kicked off the request: an XHR, a CSS document (i.e. `url()`), or a DOM element (`href` attribute, etc). I'm looking for an indicator of the nature of the content of the response, e.g. the devtools classification or something akin to a webRequest [resource type](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/webRequest/ResourceType).

**Comment by digitarald** [comment]
You will also run into the issue of `Timing-Allow-Origin` when using resource timing, so better depend on the web extension.

**Comment by chuckharmston** [comment]
@digitarald I'd need to do further testing to be sure, but I don't think it's an issue in a content script, since it's being injected into the page with the same origin. But yeah, the webextension APIs are probably better-suited for what we're looking for here.

Returning to my original question, how would you prefer I handle the unreliable measurement of request sizes?

**Comment by digitarald** [comment]
Since we sit on the source, should we fix webRequest to make it work for our use case?

In any case, 100% reliable resource sizes are not as important for our analysis.
