### ISSUE TITLE
pageAction not always loaded

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/pulse#95]
Comment from @lmorchard:

> I'm not super familiar with how Page Actions work, but it seems like I'm not getting the icon button in the URL bar on new empty tabs.
> If I restart or cause the add-on to re-install via file watcher, it sets up icons on all existing tabs. I do see a message like [pulse.webext.lib.util] Created pageAction for 10 in the console when I open a new tab with Cmd-T, but the button doesn't appear. On the other hand, if I Cmd-click a link to spawn a new tab, the icon does appear.

**Comment by chuckharmston** [comment]
I'm not seeing this personally.

@groovecoder Do you have any wisdom on making sure that the page actions load for every tab? This is how I'm currently doing it: https://github.com/mozilla/pulse/blob/master/src/webextension/background.js#L6-L15

**Comment by groovecoder** [comment]
I don't. 😢 It was one of the things users noticed about Blok too - it didn't automatically activate for existing tabs. But Blok watched all network requests and created the pageAction as soon as it saw a tracker request, so users tended to see it as soon as they refreshed any existing tab.
